# Generated by Django 2.1.7 on 2019-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.TextField()),
                ('name', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
