# Generated by Django 2.1.7 on 2019-04-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
